services:
    laravel.test:
        build:
            context: './vendor/laravel/sail/runtimes/8.5'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.5/app'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            REDIS_HOST: redis
            OLLAMA_HOST: http://ollama:11434
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - redis
            - ollama
    redis:
        image: 'redis/redis-stack:latest'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
            - '${FORWARD_REDIS_INSIGHT_PORT:-8001}:8001'
        volumes:
            - './docker/redis:/data'
        environment:
            REDIS_ARGS: '--appendonly yes'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    ollama:
        image: 'ollama/ollama:latest'
        ports:
            - '${FORWARD_OLLAMA_PORT:-11434}:11434'
        volumes:
            - './docker/ollama:/root/.ollama'
        networks:
            - sail
networks:
    sail:
        driver: bridge
